# Screen
SCREEN_WIDTH : int = 1280
SCREEN_HEIGHT : int = 720

# Player
PLAYER_RADIUS : int = 20
PLAYER_TURN_SPEED : int = 300
PLAYER_SPEED : int = 200
LINE_WIDTH : int = 2

# Asteroid
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS